# Generated by Django 2.1.5 on 2020-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating1',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='film',
            name='rating2',
            field=models.FloatField(default=2.5),
        ),
    ]
