# Generated by Django 2.1.5 on 2020-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200402_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='profilePicture',
            field=models.ImageField(upload_to='profilepictures/'),
        ),
    ]
